config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :sales_people

  resources :sales_managers

  resources :finance_managers

  resources :cars

  resources :inventory_managers

  get "/summary", to: "owner#summary", as: :summary_page
  get "/soldquotes", to: "quotes#sold", as: :soldquotes_page
  get "/generator", to: "generator#generator", as: :generator_page

  resources :cars do
    member do
      get 'car_price'
    end
  end

   root 'homepage#home'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :finance_manager
  belongs_to :sales_person
  belongs_to :customer
  belongs_to :car
  validates_presence_of :quote_price, :quote_tax, :quote_total

  def self.calc_gross_profit(quotes)
   Quote.where(:quote_status => true).sum(:quote_total)
  end

  def self.calc_total_tax(quotes)
    Quote.where(:quote_status => true).sum(:quote_tax)
  end

  def self.calc_net_sales(quotes)
    Quote.where(:quote_status => true).sum(:quote_total)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  #The sold method allows the sales manager's SALES link to display a list of quotes with
  #the status set to TRUE which mean they have resulted in a sale.
  def sold
    @quotes = Quote.select{ |sold| sold.quote_status == true}
  end

  def grossprofit
    @quotes = sum(:quote_total)
  end

  def totaltax
    @quotes = sum(:quote_tax)
  end

  def netprofit
    @quotes = :quote_total - :quote_tax
  end


  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:car_id, :sales_person_id, :customer_id, :finance_manager_id, :quote_status, :quote_price, :quote_tax, :quote_total)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <div class="field">
     <%= f.label :Car_VIN %><br>
     <%= f.collection_select :car_id, Car.all, :id, :car_VIN %>
   </div>

    <div class="field">
      <%= f.label :sales_person %><br>
      <%= f.collection_select :sales_person_id, SalesPerson.all, :id, :sperson_fname %>
    </div>

  <div class="field">
    <%= f.label :customer %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= f.label :finance_manager %><br>
    <%= f.collection_select :finance_manager_id, FinanceManager.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= f.label :quote_status, "Car Sold?" %><br>
    <%= f.check_box :quote_status %>
  </div>

  <div class="field">
    <%= f.label :quote_price, "Quote Price" %><br>
    <%= f.text_field :quote_price%>
  </div>

  <div class="field">
    <%= f.label :quote_tax %><br>
    <%= f.text_field :quote_tax %>
  </div>
  <div class="field">
    <%= f.label :quote_total, "Quote Total (place mouse over here to generate total)" %><br>
    <%= f.text_field :quote_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Car VIN</th>
      <th>Sales person</th>
      <th>Customer</th>
      <th>Finance manager</th>
      <th>Car Sold?</th>
      <th>Quote price</th>
      <th>Quote tax</th>
      <th>Quote total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.car.car_VIN %></td>
        <td><%= quote.sales_person.sperson_fname %></td>
        <td><%= quote.customer.full_name %></td>
        <td><%= quote.finance_manager.full_name %></td>
        <td><%= quote.quote_status %></td>
        <td><%= number_to_currency(quote.quote_price) %></td>
        <td><%= number_to_currency(quote.quote_tax) %></td>
        <td><%= number_to_currency(quote.quote_total) %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.car_VIN %>
</p>

<p>
  <strong>Sales person:</strong>
  <%= @quote.sales_person.sperson_fname %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.full_name %>
</p>

<p>
  <strong>Finance manager:</strong>
  <%= @quote.finance_manager.full_name %>
</p>

<p>
  <strong>Car Sold?</strong>
  <%= @quote.quote_status %>
</p>

<p>
  <strong>Quote price:</strong>
  <%= number_to_currency(@quote.quote_price) %>
</p>

<p>
  <strong>Quote tax:</strong>
  <%= number_to_currency(@quote.quote_tax) %>
</p>

<p>
  <strong>Quote total:</strong>
  <%= number_to_currency(@quote.quote_total) %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/sold.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles sold</h1>

<table>
  <thead>
  <tr>
    <th>Car VIN</th>
    <th>Sales person</th>
    <th>Customer</th>
    <th>Finance manager</th>
    <th>Car Sold?</th>
    <th>Quote price</th>
    <th>Quote tax</th>
    <th>Quote total</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.car.car_VIN %></td>
        <td><%= quote.sales_person.sperson_fname %></td>
        <td><%= quote.customer.full_name %></td>
        <td><%= quote.finance_manager.full_name %></td>
        <td><%= quote.quote_status %></td>
        <td><%= number_to_currency(quote.quote_price) %></td>
        <td><%= number_to_currency(quote.quote_tax) %></td>
        <td><%= number_to_currency(quote.quote_total) %></td>
        <td><%= link_to 'Show', quote %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<p>Gross sales amount: <%= number_to_currency(Quote.calc_gross_profit(@quotes)) %></p>