config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :sales_people

  resources :sales_managers

  resources :finance_managers

  resources :cars

  resources :inventory_managers

  get "/summary", to: "owner#summary", as: :summary_page
  get "/soldquotes", to: "quotes#sold", as: :soldquotes_page
  get "/generator", to: "generator#generator", as: :generator_page

  resources :cars do
    member do
      get 'car_price'
    end
  end

   root 'homepage#home'

end

app/models/finance_manager.rb
class FinanceManager < ActiveRecord::Base
  has_many :quotes

  def full_name
    "#{fman_fname} #{fman_lname}"
  end
end

app/controllers/finance_managers_controller.rb
class FinanceManagersController < ApplicationController
  before_action :set_finance_manager, only: [:show, :edit, :update, :destroy]

  # GET /finance_managers
  # GET /finance_managers.json
  def index
    @finance_managers = FinanceManager.all
  end

  # GET /finance_managers/1
  # GET /finance_managers/1.json
  def show
  end

  # GET /finance_managers/new
  def new
    @finance_manager = FinanceManager.new
  end

  # GET /finance_managers/1/edit
  def edit
  end

  # POST /finance_managers
  # POST /finance_managers.json
  def create
    @finance_manager = FinanceManager.new(finance_manager_params)

    respond_to do |format|
      if @finance_manager.save
        format.html { redirect_to @finance_manager, notice: 'Finance manager was successfully created.' }
        format.json { render :show, status: :created, location: @finance_manager }
      else
        format.html { render :new }
        format.json { render json: @finance_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finance_managers/1
  # PATCH/PUT /finance_managers/1.json
  def update
    respond_to do |format|
      if @finance_manager.update(finance_manager_params)
        format.html { redirect_to @finance_manager, notice: 'Finance manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance_manager }
      else
        format.html { render :edit }
        format.json { render json: @finance_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finance_managers/1
  # DELETE /finance_managers/1.json
  def destroy
    @finance_manager.destroy
    respond_to do |format|
      format.html { redirect_to finance_managers_url, notice: 'Finance manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance_manager
      @finance_manager = FinanceManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_manager_params
      params.require(:finance_manager).permit(:fman_fname, :fman_lname)
    end
end

app/helpers/finance_managers_helper.rb
module FinanceManagersHelper
end

app/views/finance_managers/_form.html.erb
<%= form_for(@finance_manager) do |f| %>
  <% if @finance_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance_manager.errors.count, "error") %> prohibited this finance_manager from being saved:</h2>

      <ul>
      <% @finance_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fman_fname %><br>
    <%= f.text_field :fman_fname %>
  </div>
  <div class="field">
    <%= f.label :fman_lname %><br>
    <%= f.text_field :fman_lname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finance_managers/edit.html.erb
<h1>Editing Finance Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance_manager %> |
<%= link_to 'Back', finance_managers_path %>

app/views/finance_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Finance Managers</h1>

<table>
  <thead>
    <tr>
      <th>Fman fname</th>
      <th>Fman lname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finance_managers.each do |finance_manager| %>
      <tr>
        <td><%= finance_manager.fman_fname %></td>
        <td><%= finance_manager.fman_lname %></td>
        <td><%= link_to 'Show', finance_manager %></td>
        <td><%= link_to 'Edit', edit_finance_manager_path(finance_manager) %></td>
        <td><%= link_to 'Destroy', finance_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance manager', new_finance_manager_path %>

app/views/finance_managers/new.html.erb
<h1>New Finance Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', finance_managers_path %>

app/views/finance_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fman fname:</strong>
  <%= @finance_manager.fman_fname %>
</p>

<p>
  <strong>Fman lname:</strong>
  <%= @finance_manager.fman_lname %>
</p>

<%= link_to 'Edit', edit_finance_manager_path(@finance_manager) %> |
<%= link_to 'Back', finance_managers_path %>