config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :sales_people

  resources :sales_managers

  resources :finance_managers

  resources :cars

  resources :inventory_managers

  get "/summary", to: "owner#summary", as: :summary_page
  get "/soldquotes", to: "quotes#sold", as: :soldquotes_page
  get "/generator", to: "generator#generator", as: :generator_page

  resources :cars do
    member do
      get 'car_price'
    end
  end

   root 'homepage#home'

end

app/models/inventory_manager.rb
class InventoryManager < ActiveRecord::Base
  has_many :cars
end

app/controllers/inventory_managers_controller.rb
class InventoryManagersController < ApplicationController
  before_action :set_inventory_manager, only: [:show, :edit, :update, :destroy]

  # GET /inventory_managers
  # GET /inventory_managers.json
  def index
    @inventory_managers = InventoryManager.all
  end

  # GET /inventory_managers/1
  # GET /inventory_managers/1.json
  def show
  end

  # GET /inventory_managers/new
  def new
    @inventory_manager = InventoryManager.new
  end

  # GET /inventory_managers/1/edit
  def edit
  end

  # POST /inventory_managers
  # POST /inventory_managers.json
  def create
    @inventory_manager = InventoryManager.new(inventory_manager_params)

    respond_to do |format|
      if @inventory_manager.save
        format.html { redirect_to @inventory_manager, notice: 'Inventory manager was successfully created.' }
        format.json { render :show, status: :created, location: @inventory_manager }
      else
        format.html { render :new }
        format.json { render json: @inventory_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_managers/1
  # PATCH/PUT /inventory_managers/1.json
  def update
    respond_to do |format|
      if @inventory_manager.update(inventory_manager_params)
        format.html { redirect_to @inventory_manager, notice: 'Inventory manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_manager }
      else
        format.html { render :edit }
        format.json { render json: @inventory_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_managers/1
  # DELETE /inventory_managers/1.json
  def destroy
    @inventory_manager.destroy
    respond_to do |format|
      format.html { redirect_to inventory_managers_url, notice: 'Inventory manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_manager
      @inventory_manager = InventoryManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_manager_params
      params.require(:inventory_manager).permit(:iman_fname, :iman_lname)
    end
end

app/helpers/inventory_managers_helper.rb
module InventoryManagersHelper
end

app/views/inventory_managers/_form.html.erb
<%= form_for(@inventory_manager) do |f| %>
  <% if @inventory_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_manager.errors.count, "error") %> prohibited this inventory_manager from being saved:</h2>

      <ul>
      <% @inventory_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :iman_fname %><br>
    <%= f.text_field :iman_fname %>
  </div>
  <div class="field">
    <%= f.label :iman_lname %><br>
    <%= f.text_field :iman_lname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_managers/edit.html.erb
<h1>Editing Inventory Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_manager %> |
<%= link_to 'Back', inventory_managers_path %>

app/views/inventory_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inventory Managers</h1>

<table>
  <thead>
    <tr>
      <th>Iman fname</th>
      <th>Iman lname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_managers.each do |inventory_manager| %>
      <tr>
        <td><%= inventory_manager.iman_fname %></td>
        <td><%= inventory_manager.iman_lname %></td>
        <td><%= link_to 'Show', inventory_manager %></td>
        <td><%= link_to 'Edit', edit_inventory_manager_path(inventory_manager) %></td>
        <td><%= link_to 'Destroy', inventory_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory manager', new_inventory_manager_path %>

app/views/inventory_managers/new.html.erb
<h1>New Inventory Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_managers_path %>

app/views/inventory_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iman fname:</strong>
  <%= @inventory_manager.iman_fname %>
</p>

<p>
  <strong>Iman lname:</strong>
  <%= @inventory_manager.iman_lname %>
</p>

<%= link_to 'Edit', edit_inventory_manager_path(@inventory_manager) %> |
<%= link_to 'Back', inventory_managers_path %>