config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :sales_people

  resources :sales_managers

  resources :finance_managers

  resources :cars

  resources :inventory_managers

  get "/summary", to: "owner#summary", as: :summary_page
  get "/soldquotes", to: "quotes#sold", as: :soldquotes_page
  get "/generator", to: "generator#generator", as: :generator_page

  resources :cars do
    member do
      get 'car_price'
    end
  end

   root 'homepage#home'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :inventory_manager
  has_one :quote
  validates_presence_of :car_VIN, :car_make, :car_model
  paginates_per 10

  def self.search(search, car_VIN, car_model, car_color)
    if search
      where('car_VIN LIKE ? OR car_model LIKE ? OR car_color LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      where(nil)
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    #@cars = Car.all
    @cars = Car.search(params[:search], params[:car_VIN], params[:car_model], params[:car_color]).page(params[:page])
  end

  def paginates_per
    @cars = Car.order(:car_make).page params[:page]
  end


  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  def car_price
    logger.info "Calling car price"
    car = Car.find(params[:id])
    render json: car
  end


  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:inventory_manager_id, :car_VIN, :car_make, :car_model, :car_color, :car_price)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inventory_manager %><br>
    <%= f.collection_select :inventory_manager_id, InventoryManager.all, :id, :iman_fname %>
  </div>
  <div class="field">
    <%= f.label :car_VIN %><br>
    <%= f.text_field :car_VIN %>
  </div>
  <div class="field">
    <%= f.label :car_make %><br>
    <%= f.text_field :car_make %>
  </div>
  <div class="field">
    <%= f.label :car_model %><br>
    <%= f.text_field :car_model %>
  </div>
  <div class="field">
    <%= f.label :car_color %><br>
    <%= f.text_field :car_color %>
  </div>
  <div class="field">
    <%= f.label :car_price %><br>
    <%= f.text_field :car_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>


<!--
Starting the search forms here.
-->
<%= form_tag cars_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search], :placeholder => "Car VIN, model or color" %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<!--
Pagination code
-->
<%= paginate @cars %>




<table>
  <thead>
    <tr>
      <th>Inventory manager</th>
      <th>Car vin</th>
      <th>Car make</th>
      <th>Car model</th>
      <th>Car color</th>
      <th>Car price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.inventory_manager.iman_fname %></td>
        <td><%= car.car_VIN %></td>
        <td><%= car.car_make %></td>
        <td><%= car.car_model %></td>
        <td><%= car.car_color %></td>
        <td><%= number_to_currency(car.car_price) %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inventory manager:</strong>
  <%= @car.inventory_manager.iman_fname %>
</p>

<p>
  <strong>Car vin:</strong>
  <%= @car.car_VIN %>
</p>

<p>
  <strong>Car make:</strong>
  <%= @car.car_make %>
</p>

<p>
  <strong>Car model:</strong>
  <%= @car.car_model %>
</p>

<p>
  <strong>Car color:</strong>
  <%= @car.car_color %>
</p>

<p>
  <strong>Car price:</strong>
  <%= number_to_currency(@car.car_price) %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>